name: portfolio
description: "Starry Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.3
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.7
  shared_preferences: ^2.3.5
  dio: ^5.7.0
  flutter_staggered_animations: ^1.1.1
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  badges: ^3.1.2
  sliver_tools: ^0.2.12
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  mocktail: ^1.0.4
  bloc_test: 9.1.7
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
        - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
        - asset: assets/fonts/RobotoMono-ExtraLightItalic.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Light.ttf
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
        - asset: assets/fonts/RobotoMono-SemiBoldItalic.ttf
        - asset: assets/fonts/RobotoMono-Thin.ttf
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
